apiVersion: v1
data:
  alertmanager.yaml: Z2xvYmFsOgogIHNsYWNrX2FwaV91cmw6IGh0dHBzOi8vaG9va3Muc2xhY2suY29tL3NlcnZpY2VzL0FQSV9VUkxfU0VDUkVUCgpyb3V0ZToKICBncm91cF9ieTogW2NsdXN0ZXJdCiAgIyBJZiBhbiBhbGVydCBpc24ndCBjYXVnaHQgYnkgYSByb3V0ZSwgc2VuZCBpdCBzbGFjay4KICByZWNlaXZlcjogc2xhY2stYWxsCiAgcm91dGVzOgogICAgLSBtYXRjaDoKICAgICAgICBzZXZlcml0eTogc2xhY2sKICAgICAgcmVjZWl2ZXI6IHNsYWNrLWFsbAoKCnJlY2VpdmVyczoKLSBuYW1lOiAnc2xhY2stYWxsJwogIHNsYWNrX2NvbmZpZ3M6CiAgLSBjaGFubmVsOiAnI3NvY2tzaG9wLW9wcycKICAgIHNlbmRfcmVzb2x2ZWQ6IHRydWUKICAgIHRpdGxlOiAie3sgcmFuZ2UgLkFsZXJ0cyB9fXt7IC5Bbm5vdGF0aW9ucy5zdW1tYXJ5IH19XG57eyBlbmQgfX0iCiAgICB0ZXh0OiAie3sgcmFuZ2UgLkFsZXJ0cyB9fXt7IC5Bbm5vdGF0aW9ucy5kZXNjcmlwdGlvbiB9fVxue3sgZW5kIH19IgogICAgYXBpX3VybDogaHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvQVBJX1VSTF9TRUNSRVQK
kind: Secret
metadata:
  name: alertmanager-main
  namespace: monitoring
type: Opaque
