---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    fabric8.io/git-commit: eebd5071f981a551f4e846fdb672110171cddd93
    fabric8.io/iconUrl: img/icons/camel.svg
    fabric8.io/git-branch: master
    fabric8.io/metrics-path: dashboard/file/camel-routes.json/?var-project=shop-catalogue-api-aggregator&var-version=1.0.0-SNAPSHOT
  labels:
    app: shop-catalogue-aggregator
    provider: fabric8
    version: 1.0.0-SNAPSHOT
    group: io.github.microservices.demo
  name: shop-catalogue-api-aggregator
  namespace: sock-shop
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: shop-catalogue-aggregator
      provider: fabric8
      group: io.github.microservices.demo
  template:
    metadata:
      annotations:
        fabric8.io/git-commit: eebd5071f981a551f4e846fdb672110171cddd93
        fabric8.io/iconUrl: img/icons/camel.svg
        fabric8.io/git-branch: master
        fabric8.io/metrics-path: dashboard/file/camel-routes.json/?var-project=shop-catalogue-api-aggregator&var-version=1.0.0-SNAPSHOT
      labels:
        app: shop-catalogue-aggregator
        provider: fabric8
        version: 1.0.0-SNAPSHOT
        group: io.github.microservices.demo
    spec:
      containers:
        - env:
            - name: SPRING_APPLICATION_JSON
              value: '{"server":{"undertow":{"io-threads":1, "worker-threads":2 }}}'
            - name: SOCKS_CATALOGUE_HOST
              value: "catalogue"
            - name: SHOES_CATALOGUE_HOST
              value: "shoes-catalogue-application:8080"
            - name: TRACING_ENDPOINT
              value: "http://jaeger-collector.jaeger.svc:14268/api/traces"
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: quay.io/rafaeltuelho/shop-catalogue-aggregator:latest
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
          name: spring-boot
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 9779
              name: prometheus
              protocol: TCP
            - containerPort: 8778
              name: jolokia
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
          resources:
            limits:
              cpu: "1.0"
              memory: 256Mi
            requests:
              cpu: "0.2"
              memory: 256Mi
          securityContext:
            privileged: false
