---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/git-commit: eebd5071f981a551f4e846fdb672110171cddd93
    fabric8.io/iconUrl: img/icons/camel.svg
    fabric8.io/git-branch: master
    prometheus.io/scrape: "true"
    prometheus.io/port: "9779"
  labels:
    expose: "true"
    app: shop-catalogue-aggregator
    provider: fabric8
    version: 1.0.0-SNAPSHOT
    group: io.github.microservices.demo
  name: shop-catalogue-aggregator
  namespace: sock-shop
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: http-metrics
      port: 9779
      protocol: TCP
      targetPort: 9779
  selector:
    app: shop-catalogue-aggregator
    provider: fabric8
    group: io.github.microservices.demo
