---
apiVersion: v1
kind: Service
metadata:
  name: front-end
  labels:
    name: front-end
    prometheus-scrape: yes
  namespace: sock-shop
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8079
      nodePort: 30000
  selector:
    name: front-end
